import React from "react"
import Head from "next/head"
import Header from "./header"

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>ListIt - Local shopping in New York City</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen min-w-screen flex flex-col">
        <Header />
        <main className="min-w-screen max-w-[1280px] mx-auto flex-1">
          {children}
        </main>
      </div>
    </>
  )
}

export default Layout
