import React, { useState } from "react"
import Head from "next/head"
import Header from "./header"
import Footer from "./footer"

function Layout({ children, className = "" }) {
  return (
    <>
      <Head>
        <title>ListIt - Local shopping in Bay Ridge, Brooklyn</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen flex flex-col bg-gray-100">
        <Header />
        <main className="flex-1 mx-auto w-full pt-5 pb-11 layout__container">
          {children}
        </main>
        <Footer />
      </div>
    </>
  )
}

export default Layout
